package src.gui.measurementGUI;

import javafx.scene.control.Label;
import javafx.scene.layout.VBox;
import measurements.Measurements;
import src.gui.elements.Dropdown;

/**
 * the dropdown menu is being created by using the interface Dropdown.<br><br>
 * 
 * 
 * <b> TODO</b> using the users supplied activities.
 * @author mathieu
 * @version 08/23/2018
 */

public class Activity implements Dropdown {
	static Measurements m;
	String[] activiteiten = { "werk", "ontspanning", "reizen", "sociaal", "sporten" };

	public VBox activiteitVBox() {
		VBox temp = new VBox();
		Label text = new Label("wat ben je nu aan het doen?");
		temp.getChildren().addAll(text, dropDownVBox(activiteiten));
		return temp;

	}

	/**
	 * 
	 * @param obj - sets the right reference to save the data that is generated by the used input
	 */
	public static void setM(Measurements obj) {
		m = obj;
	}

	/**
	 * @param oldValue - not needed here
	 */
	@Override
	public void actionComboBox(String oldValue, String newValue) {
		m.setActivity(newValue);

	}

}
